In [3]:
import torch
from torch_geometric.data import Data
from torch_geometric.data import InMemoryDataset
from torch_geometric.data import Dataset
import pandas as pd

import statistics
from tqdm import tqdm
import numpy as np

import random
import os
import matplotlib.pyplot as plt

import time

In [4]:
import torch
from torch_geometric.data import InMemoryDataset
from tqdm import tqdm
from torch_geometric.data import Dataset
# from torch.utils.data import DataLoader
from torch_geometric.data import DataLoader

import torch.nn.functional as F
import torch.nn as nn
from torch_geometric.nn import GCNConv
from torch_geometric.nn import GATConv
import sklearn
from math import sqrt
import random
from tqdm import tqdm

import warnings
warnings.filterwarnings("ignore")

In [25]:
loss = nn.L1Loss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input[0], target[0])
output.backward()

In [26]:
output

tensor(1.5908, grad_fn=<MeanBackward0>)

In [27]:
input[0]

tensor([-0.1308,  2.3050, -2.1242,  2.3868,  1.2282],
       grad_fn=<SelectBackward0>)

In [28]:
target[0]

tensor([-1.6012,  1.5109, -0.3496, -0.1944, -0.1054])

In [36]:
error0 = torch.abs(input[0] - target[0])

In [37]:
error0

tensor([1.4704, 0.7941, 1.7747, 2.5812, 1.3336], grad_fn=<AbsBackward0>)

In [38]:
torch.mean(error0)

tensor(1.5908, grad_fn=<MeanBackward0>)

In [8]:
input

tensor([[ 0.7806, -1.4900, -0.6720,  0.6056, -0.4471],
        [ 0.5553,  0.2758, -0.1883,  0.1101, -0.9476],
        [ 0.0738, -0.9548, -1.5159,  0.4319, -1.3152]], requires_grad=True)

In [10]:
target

tensor([[ 3.2389e-01,  9.8141e-01,  8.9339e-01,  4.0574e-01, -8.4906e-01],
        [ 2.0732e+00,  8.4466e-01, -1.1997e+00,  4.6197e-01, -1.0804e-03],
        [-2.7619e-01, -1.6803e+00, -2.9260e-01,  1.1966e-01, -5.7893e-01]])

In [12]:
error = input - target

In [22]:
(torch.norm(error[0]) + torch.norm(error[1]) + torch.norm(error[2]))/3

tensor(2.2748, grad_fn=<DivBackward0>)

In [17]:
torch.sum(error)/3

tensor(-1.9747, grad_fn=<DivBackward0>)

In [21]:
torch.norm(error[2])

tensor(1.6687, grad_fn=<NormBackward1>)